<template>
  <div class="app-projects-twitter">

    <div class="container">
      <h3>Twitter datascience project</h3>

      <p>
        My datascience project is collection every tweet in Berlin.
        Tweets are saved to a <a href="https://www.mongodb.com/">MongoDB</a> for further calculations.
        The calculations are made by another program, which is build with the
        Java <a href="https://spring.io/">SpringBoot</a> framework, it is hosting a REST Web Service.
        It also utilises the MongoDB Aggregation framework and MongoDB mapReduce to perform very quickly.
        This website queries the API and shows the result of the calculations in charts generated by the <a href="http://www.chartjs.org/">Chart.js</a> library.
        It is possible to narrow down the results to the date range selected in the input fields.
      </p>

      <section class="row">
        <div class="col s12 m5">
          <app-date-picker :value="fromDate" :max="toDate" @input="setFromDate" placeholder="From"></app-date-picker>
        </div>
        <div class="col s12 m5">
          <app-date-picker :value="toDate" :min="fromDate" :max="today" @input="setToDate" placeholder="To"></app-date-picker>
        </div>
        <div class="col s12 m2">
          <a class="waves-effect waves-light btn" @click="loadData"><i class="material-icons left">loop</i>Refresh</a>
        </div>

        <div class="col s12">
          <h4>Tweets per weekday</h4>

          <p>This shows you have many tweets are made per weekday.</p>

          <div v-if="tweetsPerWeekday.length === 0">
            <div key="preloader" class="center-align">
              <div class="preloader-wrapper big active">
                <div class="spinner-layer spinner-blue-only">
                  <div class="circle-clipper left">
                    <div class="circle"></div>
                  </div>
                  <div class="gap-patch">
                    <div class="circle"></div>
                  </div>
                  <div class="circle-clipper right">
                    <div class="circle"></div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div v-if="tweetsPerWeekday.length > 0">
            <app-tweets-per-weekday></app-tweets-per-weekday>
          </div>
        </div>

        <div class="col s12">
          <h4>Tweets per hour</h4>

          <p>This diagram shows you a amount of tweets made every hour in the specified date range.</p>


          <div v-if="tweetsPerHour.length === 0">
            <div key="preloader" class="center-align">
              <div class="preloader-wrapper big active">
                <div class="spinner-layer spinner-blue-only">
                  <div class="circle-clipper left">
                    <div class="circle"></div>
                  </div>
                  <div class="gap-patch">
                    <div class="circle"></div>
                  </div>
                  <div class="circle-clipper right">
                    <div class="circle"></div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div v-if="tweetsPerHour.length > 0">
            <app-tweets-per-hour></app-tweets-per-hour>
          </div>

        </div>
      </section>

      <section class="row">
        <div class="col s12">
          <h4>Tagcloud of most used hashtags</h4>

          <p>Here you see an impression of the most used hash tags in the specified date period.</p>

          <div v-if="mostUsedHashTags !== null && mostUsedHashTags.length === 0">
            <div key="preloader" class="center-align">
              <div class="preloader-wrapper big active">
                <div class="spinner-layer spinner-blue-only">
                  <div class="circle-clipper left">
                    <div class="circle"></div>
                  </div>
                  <div class="gap-patch">
                    <div class="circle"></div>
                  </div>
                  <div class="circle-clipper right">
                    <div class="circle"></div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div v-if="mostUsedHashTags === null || mostUsedHashTags.length > 0">
              <!-- Modal Trigger -->
              <a class="waves-effect waves-light btn" ref="modalTrigger">Show list</a>

              <hr>

              <div class="tagcloud" ref="tagcloud"></div>

              <!-- Modal Structure -->
              <div class="modal" ref="modal">
                <div class="modal-content">
                  <h4>List of most used hash tags</h4>
                  <table class="striped taglist">
                    <thead>
                      <tr>
                        <th class="min"></th>
                        <th>Text</th>
                        <th class="min">#</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr v-for="(hashTag, index) in mostUsedHashTags" :key="hashTag">
                        <td>{{ index + 1 }}</td>
                        <td >{{ hashTag.text }}</td>
                        <td>{{ hashTag.count }}</td>
                      </tr>
                    </tbody>
                  </table>
                </div>
                <div class="modal-footer">
                  <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat">Close</a>
                </div>
              </div>


          </div>

        </div>
      </section>

    </div>

  </div>
</template>

<style scoped>
table.taglist > tbody > tr > td:first-of-type + td {
  word-wrap: break-word;
  word-break: break-all;
}

.min {
  width: 0%;
}

.max {
  width: 100%;
}
</style>

<script>
import { mapState, mapActions, mapMutations, mapGetters } from 'vuex'
import $ from 'jquery'
import 'jqcloud2/dist/jqcloud'
import 'jqcloud2/dist/jqcloud.css'
import AppTweetsPerWeekday from '@/components/charts/TweetsPerWeekday'
import AppTweetsPerHour from '@/components/charts/TweetsPerHour'
import AppDatePicker from '@/components/input/DatePicker'

export default {
  name: 'app-projects-twitter',
  components: {
    AppTweetsPerWeekday,
    AppTweetsPerHour,
    AppDatePicker
  },
  head: {
    title: {
      inner: 'Projects - Twitter'
    }
  },
  mounted () {
    this.loadData()
  },
  destroyed () {
    this.clearMostUsedHashTags()
  },
  computed: {
    ...mapState(['projects']),
    ...mapGetters({
      mostUsedHashTags: 'twitterProjectMostUsedHashTags',
      tweetsPerHour: 'twitterProjectTweetsPerHour',
      tweetsPerWeekday: 'twitterProjectTweetsPerWeekday'
    }),
    ...mapGetters({
      fromDate: 'twitterProjectFromDate',
      toDate: 'twitterProjectToDate'
    }),
    today () {
      let date = new Date()
      date.setDate(new Date().getDate())
      date.setHours(0)
      date.setMinutes(0)
      date.setSeconds(0)
      date.setMilliseconds(0)

      return date
    }
  },
  methods: {
    ...mapActions(['fetchMostUsedHashTags', 'fetchTweetsPerHour', 'fetchTweetsPerWeekday']),
    ...mapMutations({
      clearMostUsedHashTags: 'CLEAR_MOST_USED_HASH_TAGS',
      clearTweetsPerHour: 'CLEAR_TWEETS_PER_HOUR',
      clearTweetsPerWeekday: 'CLEAR_TWEETS_PER_WEEKDAY',
      setFromDate: 'SET_TWITTER_PROJECT_FROM_DATE',
      setToDate: 'SET_TWITTER_PROJECT_TO_DATE'
    }),
    loadData () {
      this.clearMostUsedHashTags()
      this.fetchMostUsedHashTags({ fromDate: this.fromDate, toDate: this.toDate }).then(() => {
        $(this.$refs.tagcloud).jQCloud(this.mostUsedHashTags, {
          height: 350
        })

        $(this.$refs.modal).modal()
        $(this.$refs.modalTrigger).click(() => {
          $(this.$refs.modal).modal('open')
        })
      })

      this.clearTweetsPerHour()
      this.fetchTweetsPerHour({ fromDate: this.fromDate, toDate: this.toDate }).then(() => {

      })

      this.clearTweetsPerWeekday()
      this.fetchTweetsPerWeekday({ fromDate: this.fromDate, toDate: this.toDate }).then(() => {

      })
    }
  }
}
</script>
